# Generated by Django 4.2.11 on 2026-02-20 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_seat_booking_status_alter_seat_seat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookings.movie'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookings.seat'),
        ),
    ]
