# Generated by Django 4.2.11 on 2026-03-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
